# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1    
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
      - name: Restore Packages
        run: nuget restore WebFormsDependencyInjectionDemo.sln
      - name: Build DotNET
        run: |
         MSBuild.exe $Env:GITHUB_WORKSPACE\WebFormsDependencyInjectionDemo.sln
